/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardPagesPageIdRouteImport } from './routes/dashboard/pages/$pageId'

import { Route as DashboardAgentsRouteImport } from './routes/dashboard/agents'
import { Route as DashboardAdminReplyHelpersRouteImport } from './routes/dashboard/admin/reply-helpers' // ✅ NEW

const DashboardAgentsRoute = DashboardAgentsRouteImport.update({
  id: '/dashboard/agents',
  path: '/dashboard/agents',
  getParentRoute: () => rootRouteImport,
} as any)

const DashboardAdminReplyHelpersRoute = DashboardAdminReplyHelpersRouteImport.update({
  id: '/dashboard/admin/reply-helpers',
  path: '/dashboard/admin/reply-helpers',
  getParentRoute: () => rootRouteImport,
} as any)

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPagesPageIdRoute = DashboardPagesPageIdRouteImport.update({
  id: '/dashboard/pages/$pageId',
  path: '/dashboard/pages/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/pages/$pageId': typeof DashboardPagesPageIdRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/admin/reply-helpers': typeof DashboardAdminReplyHelpersRoute // ✅ NEW
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/pages/$pageId': typeof DashboardPagesPageIdRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/admin/reply-helpers': typeof DashboardAdminReplyHelpersRoute // ✅ NEW
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/pages/$pageId': typeof DashboardPagesPageIdRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/admin/reply-helpers': typeof DashboardAdminReplyHelpersRoute // ✅ NEW
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/unauthorized'
    | '/dashboard'
    | '/dashboard/pages/$pageId'
    | '/dashboard/agents'
    | '/dashboard/admin/reply-helpers' // ✅ NEW
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/unauthorized'
    | '/dashboard'
    | '/dashboard/pages/$pageId'
    | '/dashboard/agents'
    | '/dashboard/admin/reply-helpers' // ✅ NEW
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/unauthorized'
    | '/dashboard/'
    | '/dashboard/pages/$pageId'
    | '/dashboard/agents'
    | '/dashboard/admin/reply-helpers' // ✅ NEW
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardPagesPageIdRoute: typeof DashboardPagesPageIdRoute
  DashboardAgentsRoute: typeof DashboardAgentsRoute
  DashboardAdminReplyHelpersRoute: typeof DashboardAdminReplyHelpersRoute // ✅ NEW
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/pages/$pageId': {
      id: '/dashboard/pages/$pageId'
      path: '/dashboard/pages/$pageId'
      fullPath: '/dashboard/pages/$pageId'
      preLoaderRoute: typeof DashboardPagesPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/agents': {
      id: '/dashboard/agents'
      path: '/dashboard/agents'
      fullPath: '/dashboard/agents'
      preLoaderRoute: typeof DashboardAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/reply-helpers': {
      id: '/dashboard/admin/reply-helpers'
      path: '/dashboard/admin/reply-helpers'
      fullPath: '/dashboard/admin/reply-helpers'
      preLoaderRoute: typeof DashboardAdminReplyHelpersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPagesPageIdRoute: DashboardPagesPageIdRoute,
  DashboardAgentsRoute,
  DashboardAdminReplyHelpersRoute, // ✅ NEW
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
