/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardPagesPageIdRouteImport } from './routes/dashboard/pages/$pageId'

import { Route as DashboardAgentsRouteImport } from './routes/dashboard/agents'
import { Route as DashboardAdminReplyHelpersRouteImport } from './routes/dashboard/admin/reply-helpers'
import { Route as SmartCatalogRouteImport } from './routes/smart-catalog/smart-catalog'

import { Route as SmartCatalogPageIdRouteImport } from './routes/smart-catalog/$pageId'
import { Route as SmartCatalogPageIdAdminRouteImport } from './routes/smart-catalog/$pageId/admin'

import { Route as DashboardFlowRouteImport } from './routes/dashboard/flow'

import { Route as TrackTrackingIdRouteImport } from './routes/track/$tracking_id'

const TrackTrackingIdRoute = TrackTrackingIdRouteImport.update({
  id: '/track/$tracking_id',
  path: '/track/$tracking_id',
  getParentRoute: () => rootRouteImport,
} as any)


const DashboardAgentsRoute = DashboardAgentsRouteImport.update({
  id: '/dashboard/agents',
  path: '/dashboard/agents',
  getParentRoute: () => rootRouteImport,
} as any)

const DashboardFlowRoute = DashboardFlowRouteImport.update({
  id: '/dashboard/flow',
  path: '/dashboard/flow',
  getParentRoute: () => rootRouteImport,
} as any)

const SmartCatalogRoute = SmartCatalogRouteImport.update({
  id: '/smart-catalog',
  path: '/smart-catalog',
  getParentRoute: () => rootRouteImport,
} as any)

const SmartCatalogPageIdRoute = SmartCatalogPageIdRouteImport.update({
  id: '/smart-catalog/$pageId',
  path: '/smart-catalog/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)

const SmartCatalogPageIdAdminRoute = SmartCatalogPageIdAdminRouteImport.update({
  id: '/smart-catalog/$pageId/admin',
  path: '/smart-catalog/$pageId/admin',
  getParentRoute: () => rootRouteImport,
} as any)

const DashboardAdminReplyHelpersRoute = DashboardAdminReplyHelpersRouteImport.update({
  id: '/dashboard/admin/reply-helpers',
  path: '/dashboard/admin/reply-helpers',
  getParentRoute: () => rootRouteImport,
} as any)

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPagesPageIdRoute = DashboardPagesPageIdRouteImport.update({
  id: '/dashboard/pages/$pageId',
  path: '/dashboard/pages/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/pages/$pageId': typeof DashboardPagesPageIdRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/admin/reply-helpers': typeof DashboardAdminReplyHelpersRoute
  '/smart-catalog': typeof SmartCatalogRoute
  '/smart-catalog/$pageId': typeof SmartCatalogPageIdRoute
  '/smart-catalog/$pageId/admin': typeof SmartCatalogPageIdAdminRoute
  '/dashboard/flow': typeof DashboardFlowRoute
  '/track/$tracking_id': typeof TrackTrackingIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/pages/$pageId': typeof DashboardPagesPageIdRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/admin/reply-helpers': typeof DashboardAdminReplyHelpersRoute // ✅ NEW
  '/smart-catalog': typeof SmartCatalogRoute                // ✅ NEW
  '/smart-catalog/$pageId': typeof SmartCatalogPageIdRoute
  '/smart-catalog/$pageId/admin': typeof SmartCatalogPageIdAdminRoute
  '/dashboard/flow': typeof DashboardFlowRoute              // ✅ NEW
  '/track/$tracking_id': typeof TrackTrackingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/pages/$pageId': typeof DashboardPagesPageIdRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/admin/reply-helpers': typeof DashboardAdminReplyHelpersRoute // ✅ NEW
  '/smart-catalog': typeof SmartCatalogRoute                // ✅ NEW
  '/smart-catalog/$pageId': typeof SmartCatalogPageIdRoute
  '/smart-catalog/$pageId/admin': typeof SmartCatalogPageIdAdminRoute
  '/dashboard/flow': typeof DashboardFlowRoute              // ✅ NEW
  '/track/$tracking_id': typeof TrackTrackingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
  | '/'
  | '/login'
  | '/signup'
  | '/unauthorized'
  | '/dashboard'
  | '/dashboard/pages/$pageId'
  | '/dashboard/agents'
  | '/dashboard/admin/reply-helpers' // ✅ NEW
  | '/smart-catalog'                                      // ✅ NEW
  | '/dashboard/flow'                                     // ✅ NEW
  | '/track/$tracking_id'
  fileRoutesByTo: FileRoutesByTo
  to:
  | '/'
  | '/login'
  | '/signup'
  | '/unauthorized'
  | '/dashboard'
  | '/dashboard/pages/$pageId'
  | '/dashboard/agents'
  | '/dashboard/admin/reply-helpers' // ✅ NEW
  | '/smart-catalog'                                      // ✅ NEW
  | '/smart-catalog/$pageId'
  | '/smart-catalog/$pageId/admin'
  | '/dashboard/flow'                                     // ✅ NEW
  | '/track/$tracking_id'
  id:
  | '__root__'
  | '/'
  | '/login'
  | '/signup'
  | '/unauthorized'
  | '/dashboard/'
  | '/dashboard/pages/$pageId'
  | '/dashboard/agents'
  | '/dashboard/admin/reply-helpers' // ✅ NEW
  | '/smart-catalog'                                      // ✅ NEW
  | '/smart-catalog/$pageId'
  | '/smart-catalog/$pageId/admin'
  | '/dashboard/flow'                                     // ✅ NEW
  | '/track/$tracking_id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardPagesPageIdRoute: typeof DashboardPagesPageIdRoute
  DashboardAgentsRoute: typeof DashboardAgentsRoute
  DashboardAdminReplyHelpersRoute: typeof DashboardAdminReplyHelpersRoute // ✅ NEW
  SmartCatalogRoute: typeof SmartCatalogRoute               // ✅ NEW
  DashboardFlowRoute: typeof DashboardFlowRoute             // ✅ NEW
  TrackTrackingIdRoute: typeof TrackTrackingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/pages/$pageId': {
      id: '/dashboard/pages/$pageId'
      path: '/dashboard/pages/$pageId'
      fullPath: '/dashboard/pages/$pageId'
      preLoaderRoute: typeof DashboardPagesPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/agents': {
      id: '/dashboard/agents'
      path: '/dashboard/agents'
      fullPath: '/dashboard/agents'
      preLoaderRoute: typeof DashboardAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-catalog': {
      id: '/smart-catalog'
      path: '/smart-catalog'
      fullPath: '/smart-catalog'
      preLoaderRoute: typeof SmartCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-catalog/$pageId': {
      id: '/smart-catalog/$pageId'
      path: '/smart-catalog/$pageId'
      fullPath: '/smart-catalog/$pageId'
      preLoaderRoute: typeof SmartCatalogPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-catalog/$pageId/admin': {
      id: '/smart-catalog/$pageId/admin'
      path: '/smart-catalog/$pageId/admin'
      fullPath: '/smart-catalog/$pageId/admin'
      preLoaderRoute: typeof SmartCatalogPageIdAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/flow': {
      id: '/dashboard/flow'
      path: '/dashboard/flow'
      fullPath: '/dashboard/flow'
      preLoaderRoute: typeof DashboardFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/reply-helpers': {
      id: '/dashboard/admin/reply-helpers'
      path: '/dashboard/admin/reply-helpers'
      fullPath: '/dashboard/admin/reply-helpers'
      preLoaderRoute: typeof DashboardAdminReplyHelpersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$tracking_id': {
      id: '/track/$tracking_id'
      path: '/track/$tracking_id'
      fullPath: '/track/$tracking_id'
      preLoaderRoute: typeof TrackTrackingIdRouteImport
      parentRoute: typeof rootRouteImport
    }

  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPagesPageIdRoute: DashboardPagesPageIdRoute,
  DashboardAgentsRoute,
  DashboardAdminReplyHelpersRoute, // ✅ NEW
  SmartCatalogRoute,
  SmartCatalogPageIdRoute,        // ✅ NEW
  SmartCatalogPageIdAdminRoute,   // ✅ NEW
  DashboardFlowRoute,
  TrackTrackingIdRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
