/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardPagesPageIdRouteImport } from './routes/dashboard/pages/$pageId'

import { Route as DashboardAgentsRouteImport } from './routes/dashboard/agents'
import { Route as DashboardAdminReplyHelpersRouteImport } from './routes/dashboard/admin/reply-helpers'
import { Route as SmartCatalogRouteImport } from './routes/smart-catalog/smart-catalog'

import { Route as SmartCatalogPageIdRouteImport } from './routes/smart-catalog/$pageId'
import { Route as SmartCatalogPageIdAdminRouteImport } from './routes/smart-catalog/$pageId/admin'

import { Route as DashboardFlowRouteImport } from './routes/dashboard/flow'

import { Route as TrackTrackingIdRouteImport } from './routes/track/$tracking_id'
import { Route as DeliveryRouteImport } from './routes/delivery/delivery'

import { Route as DashboardAdminCreateDriverRouteImport } from './routes/dashboard/admin/create-driver'
import { Route as DashboardAdminDeliveriesRouteImport } from './routes/dashboard/admin/deliveries'
import { Route as DashboardDriverRouteImport } from './routes/dashboard/driver'
import { Route as DashboardAdminDriverMapRouteImport } from './routes/dashboard/admin/driver-map'
import { Route as AttendanceRouteImport } from './routes/attendance/attendance'
import { Route as AttendanceReportRouteImport } from './routes/attendance/report'
import { Route as AttendanceSettingsRouteImport } from './routes/attendance/settings'
import { Route as AttendanceAdminRolesRouteImport } from './routes/attendance/admin/roles'
import { Route as AttendanceAdminConfigRouteImport } from './routes/attendance/admin/attendance_config'
import { Route as AttendanceViewHistoryRouteImport } from './routes/attendance/viewhistory'
import { Route as AttendanceRegisterRouteImport } from './routes/attendance/register'

const AttendanceRegisterRoute = AttendanceRegisterRouteImport.update({
  id: '/attendance/register',
  path: '/attendance/register',
  getParentRoute: () => rootRouteImport,
} as any)


const AttendanceViewHistoryRoute = AttendanceViewHistoryRouteImport.update({
  id: '/attendance/viewhistory',
  path: '/attendance/viewhistory',
  getParentRoute: () => rootRouteImport,
} as any)


const AttendanceAdminRolesRoute = AttendanceAdminRolesRouteImport.update({
  id: '/attendance/admin/roles',
  path: '/attendance/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)

const AttendanceAdminConfigRoute = AttendanceAdminConfigRouteImport.update({
  id: '/attendance/admin/config',
  path: '/attendance/admin/config',
  getParentRoute: () => rootRouteImport,
} as any)


const AttendanceSettingsRoute = AttendanceSettingsRouteImport.update({
  id: '/attendance/settings',
  path: '/attendance/settings',
  getParentRoute: () => rootRouteImport,
} as any)

const AttendanceReportRoute = AttendanceReportRouteImport.update({
  id: '/attendance/report',
  path: '/attendance/report',
  getParentRoute: () => rootRouteImport,
} as any)


const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)

const DashboardAdminDriverMapRoute = DashboardAdminDriverMapRouteImport.update({
  id: '/dashboard/admin/driver-map',
  path: '/dashboard/admin/driver-map',
  getParentRoute: () => rootRouteImport,
} as any)

const DashboardAdminCreateDriverRoute = DashboardAdminCreateDriverRouteImport.update({
  id: '/dashboard/admin/create-driver',
  path: '/dashboard/admin/create-driver',
  getParentRoute: () => rootRouteImport,
} as any)

const DashboardAdminDeliveriesRoute = DashboardAdminDeliveriesRouteImport.update({
  id: '/dashboard/admin/deliveries',
  path: '/dashboard/admin/deliveries',
  getParentRoute: () => rootRouteImport,
} as any)

const DashboardDriverRoute = DashboardDriverRouteImport.update({
  id: '/dashboard/driver',
  path: '/dashboard/driver',
  getParentRoute: () => rootRouteImport,
} as any)


const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)

const TrackTrackingIdRoute = TrackTrackingIdRouteImport.update({
  id: '/track/$tracking_id',
  path: '/track/$tracking_id',
  getParentRoute: () => rootRouteImport,
} as any)


const DashboardAgentsRoute = DashboardAgentsRouteImport.update({
  id: '/dashboard/agents',
  path: '/dashboard/agents',
  getParentRoute: () => rootRouteImport,
} as any)

const DashboardFlowRoute = DashboardFlowRouteImport.update({
  id: '/dashboard/flow',
  path: '/dashboard/flow',
  getParentRoute: () => rootRouteImport,
} as any)

const SmartCatalogRoute = SmartCatalogRouteImport.update({
  id: '/smart-catalog',
  path: '/smart-catalog',
  getParentRoute: () => rootRouteImport,
} as any)

const SmartCatalogPageIdRoute = SmartCatalogPageIdRouteImport.update({
  id: '/smart-catalog/$pageId',
  path: '/smart-catalog/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)

const SmartCatalogPageIdAdminRoute = SmartCatalogPageIdAdminRouteImport.update({
  id: '/smart-catalog/$pageId/admin',
  path: '/smart-catalog/$pageId/admin',
  getParentRoute: () => rootRouteImport,
} as any)

const DashboardAdminReplyHelpersRoute = DashboardAdminReplyHelpersRouteImport.update({
  id: '/dashboard/admin/reply-helpers',
  path: '/dashboard/admin/reply-helpers',
  getParentRoute: () => rootRouteImport,
} as any)

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPagesPageIdRoute = DashboardPagesPageIdRouteImport.update({
  id: '/dashboard/pages/$pageId',
  path: '/dashboard/pages/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/pages/$pageId': typeof DashboardPagesPageIdRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/admin/reply-helpers': typeof DashboardAdminReplyHelpersRoute
  '/smart-catalog': typeof SmartCatalogRoute
  '/smart-catalog/$pageId': typeof SmartCatalogPageIdRoute
  '/smart-catalog/$pageId/admin': typeof SmartCatalogPageIdAdminRoute
  '/dashboard/flow': typeof DashboardFlowRoute
  '/track/$tracking_id': typeof TrackTrackingIdRoute
  '/delivery': typeof DeliveryRoute
  '/dashboard/admin/create-driver': typeof DashboardAdminCreateDriverRoute
  '/dashboard/admin/deliveries': typeof DashboardAdminDeliveriesRoute
  '/dashboard/driver': typeof DashboardDriverRoute
  '/dashboard/admin/driver-map': typeof DashboardAdminDriverMapRoute
  '/attendance': typeof AttendanceRoute
  '/attendance/report': typeof AttendanceReportRoute   // ✅ NEW
  '/attendance/settings': typeof AttendanceSettingsRoute
  '/attendance/admin/roles': typeof AttendanceAdminRolesRoute
  '/attendance/admin/config': typeof AttendanceAdminConfigRoute
  '/attendance/viewhistory': typeof AttendanceViewHistoryRoute
  '/attendance/register': typeof AttendanceRegisterRoute

}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/pages/$pageId': typeof DashboardPagesPageIdRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/admin/reply-helpers': typeof DashboardAdminReplyHelpersRoute // ✅ NEW
  '/smart-catalog': typeof SmartCatalogRoute                // ✅ NEW
  '/smart-catalog/$pageId': typeof SmartCatalogPageIdRoute
  '/smart-catalog/$pageId/admin': typeof SmartCatalogPageIdAdminRoute
  '/dashboard/flow': typeof DashboardFlowRoute              // ✅ NEW
  '/track/$tracking_id': typeof TrackTrackingIdRoute
  '/delivery': typeof DeliveryRoute
  '/dashboard/admin/create-driver': typeof DashboardAdminCreateDriverRoute
  '/dashboard/admin/deliveries': typeof DashboardAdminDeliveriesRoute
  '/dashboard/driver': typeof DashboardDriverRoute
  '/dashboard/admin/driver-map': typeof DashboardAdminDriverMapRoute
  '/attendance': typeof AttendanceRoute
  '/attendance/report': typeof AttendanceReportRoute   // ✅ NEW
  '/attendance/settings': typeof AttendanceSettingsRoute
  '/attendance/admin/roles': typeof AttendanceAdminRolesRoute
  '/attendance/admin/config': typeof AttendanceAdminConfigRoute
  '/attendance/viewhistory': typeof AttendanceViewHistoryRoute
  '/attendance/register': typeof AttendanceRegisterRoute

}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/pages/$pageId': typeof DashboardPagesPageIdRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/admin/reply-helpers': typeof DashboardAdminReplyHelpersRoute // ✅ NEW
  '/smart-catalog': typeof SmartCatalogRoute                // ✅ NEW
  '/smart-catalog/$pageId': typeof SmartCatalogPageIdRoute
  '/smart-catalog/$pageId/admin': typeof SmartCatalogPageIdAdminRoute
  '/dashboard/flow': typeof DashboardFlowRoute              // ✅ NEW
  '/track/$tracking_id': typeof TrackTrackingIdRoute
  '/delivery': typeof DeliveryRoute
  '/dashboard/admin/create-driver': typeof DashboardAdminCreateDriverRoute
  '/dashboard/admin/deliveries': typeof DashboardAdminDeliveriesRoute
  '/dashboard/driver': typeof DashboardDriverRoute
  '/dashboard/admin/driver-map': typeof DashboardAdminDriverMapRoute
  '/attendance': typeof AttendanceRoute
  '/attendance/report': typeof AttendanceReportRoute   // ✅ NEW
  '/attendance/settings': typeof AttendanceSettingsRoute
  '/attendance/admin/roles': typeof AttendanceAdminRolesRoute
  '/attendance/admin/config': typeof AttendanceAdminConfigRoute
  '/attendance/viewhistory': typeof AttendanceViewHistoryRoute
  '/attendance/register': typeof AttendanceRegisterRoute

}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
  | '/'
  | '/login'
  | '/signup'
  | '/unauthorized'
  | '/dashboard'
  | '/dashboard/pages/$pageId'
  | '/dashboard/agents'
  | '/dashboard/admin/reply-helpers' // ✅ NEW
  | '/smart-catalog'                                      // ✅ NEW
  | '/dashboard/flow'                                     // ✅ NEW
  | '/track/$tracking_id'
  | '/delivery'
  | '/dashboard/admin/create-driver'
  | '/dashboard/admin/deliveries'
  | '/dashboard/driver'
  | '/dashboard/admin/driver-map'
  | '/attendance/report'   // ✅ NEW
  | '/attendance/settings'
  | '/attendance/admin/roles'
  | '/attendance/admin/config'
  | '/attendance/register'


  fileRoutesByTo: FileRoutesByTo
  to:
  | '/'
  | '/login'
  | '/signup'
  | '/unauthorized'
  | '/dashboard'
  | '/dashboard/pages/$pageId'
  | '/dashboard/agents'
  | '/dashboard/admin/reply-helpers' // ✅ NEW
  | '/smart-catalog'                                      // ✅ NEW
  | '/smart-catalog/$pageId'
  | '/smart-catalog/$pageId/admin'
  | '/dashboard/flow'                                     // ✅ NEW
  | '/track/$tracking_id'
  | '/delivery'
  | '/dashboard/admin/create-driver'
  | '/dashboard/admin/deliveries'
  | '/dashboard/driver'
  | '/dashboard/admin/driver-map'
  | '/attendance'
  | '/attendance/report'   // ✅ NEW
  | '/attendance/settings'
  | '/attendance/admin/roles'
  | '/attendance/admin/config'
  | '/attendance/viewhistory'
  | '/attendance/register'

  id:
  | '__root__'
  | '/'
  | '/login'
  | '/signup'
  | '/unauthorized'
  | '/dashboard/'
  | '/dashboard/pages/$pageId'
  | '/dashboard/agents'
  | '/dashboard/admin/reply-helpers' // ✅ NEW
  | '/smart-catalog'                                      // ✅ NEW
  | '/smart-catalog/$pageId'
  | '/smart-catalog/$pageId/admin'
  | '/dashboard/flow'                                     // ✅ NEW
  | '/track/$tracking_id'
  | '/delivery'
  | '/dashboard/admin/create-driver'
  | '/dashboard/admin/deliveries'
  | '/dashboard/driver'
  | '/dashboard/admin/driver-map'
  | '/attendance'
  | '/attendance/report'   // ✅ NEW
  | '/attendance/settings'
  | '/attendance/admin/roles'
  | '/attendance/admin/config'
  | '/attendance/viewhistory'
  | '/attendance/register'

  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardPagesPageIdRoute: typeof DashboardPagesPageIdRoute
  DashboardAgentsRoute: typeof DashboardAgentsRoute
  DashboardAdminReplyHelpersRoute: typeof DashboardAdminReplyHelpersRoute // ✅ NEW
  SmartCatalogRoute: typeof SmartCatalogRoute               // ✅ NEW
  DashboardFlowRoute: typeof DashboardFlowRoute             // ✅ NEW
  TrackTrackingIdRoute: typeof TrackTrackingIdRoute
  DeliveryRoute: typeof DeliveryRoute
  DashboardAdminCreateDriverRoute: typeof DashboardAdminCreateDriverRoute
  DashboardAdminDeliveriesRoute: typeof DashboardAdminDeliveriesRoute
  DashboardDriverRoute: typeof DashboardDriverRoute
  DashboardAdminDriverMapRoute: typeof DashboardAdminDriverMapRoute
  AttendanceRoute: typeof AttendanceRoute
  AttendanceReportRoute: typeof AttendanceReportRoute       // ✅ NEW
  AttendanceSettingsRoute: typeof AttendanceSettingsRoute
  AttendanceAdminRolesRoute: typeof AttendanceAdminRolesRoute
  AttendanceAdminConfigRoute: typeof AttendanceAdminConfigRoute
  AttendanceViewHistoryRoute: typeof AttendanceViewHistoryRoute,
  AttendanceRegisterRoute: typeof AttendanceRegisterRoute

}




declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/pages/$pageId': {
      id: '/dashboard/pages/$pageId'
      path: '/dashboard/pages/$pageId'
      fullPath: '/dashboard/pages/$pageId'
      preLoaderRoute: typeof DashboardPagesPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/agents': {
      id: '/dashboard/agents'
      path: '/dashboard/agents'
      fullPath: '/dashboard/agents'
      preLoaderRoute: typeof DashboardAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/reply-helpers': {
      id: '/dashboard/admin/reply-helpers'
      path: '/dashboard/admin/reply-helpers'
      fullPath: '/dashboard/admin/reply-helpers'
      preLoaderRoute: typeof DashboardAdminReplyHelpersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/create-driver': {
      id: '/dashboard/admin/create-driver'
      path: '/dashboard/admin/create-driver'
      fullPath: '/dashboard/admin/create-driver'
      preLoaderRoute: typeof DashboardAdminCreateDriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/deliveries': {
      id: '/dashboard/admin/deliveries'
      path: '/dashboard/admin/deliveries'
      fullPath: '/dashboard/admin/deliveries'
      preLoaderRoute: typeof DashboardAdminDeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/driver': {
      id: '/dashboard/driver'
      path: '/dashboard/driver'
      fullPath: '/dashboard/driver'
      preLoaderRoute: typeof DashboardDriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-catalog': {
      id: '/smart-catalog'
      path: '/smart-catalog'
      fullPath: '/smart-catalog'
      preLoaderRoute: typeof SmartCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-catalog/$pageId': {
      id: '/smart-catalog/$pageId'
      path: '/smart-catalog/$pageId'
      fullPath: '/smart-catalog/$pageId'
      preLoaderRoute: typeof SmartCatalogPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-catalog/$pageId/admin': {
      id: '/smart-catalog/$pageId/admin'
      path: '/smart-catalog/$pageId/admin'
      fullPath: '/smart-catalog/$pageId/admin'
      preLoaderRoute: typeof SmartCatalogPageIdAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/flow': {
      id: '/dashboard/flow'
      path: '/dashboard/flow'
      fullPath: '/dashboard/flow'
      preLoaderRoute: typeof DashboardFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$tracking_id': {
      id: '/track/$tracking_id'
      path: '/track/$tracking_id'
      fullPath: '/track/$tracking_id'
      preLoaderRoute: typeof TrackTrackingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/driver-map': {
      id: '/dashboard/admin/driver-map'
      path: '/dashboard/admin/driver-map'
      fullPath: '/dashboard/admin/driver-map'
      preLoaderRoute: typeof DashboardAdminDriverMapRouteImport
      parentRoute: typeof rootRouteImport
    }

    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/report': {                     // ✅ NEW
      id: '/attendance/report'
      path: '/attendance/report'
      fullPath: '/attendance/report'
      preLoaderRoute: typeof AttendanceReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/settings': {                      // ✅ NEW
      id: '/attendance/settings'
      path: '/attendance/settings'
      fullPath: '/attendance/settings'
      preLoaderRoute: typeof AttendanceSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/admin/roles': {
      id: '/attendance/admin/roles'
      path: '/attendance/admin/roles'
      fullPath: '/attendance/admin/roles'
      preLoaderRoute: typeof AttendanceAdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/admin/config': {
      id: '/attendance/admin/config'
      path: '/attendance/admin/config'
      fullPath: '/attendance/admin/config'
      preLoaderRoute: typeof AttendanceAdminConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/viewhistory': {
      id: '/attendance/viewhistory'
      path: '/attendance/viewhistory'
      fullPath: '/attendance/viewhistory'
      preLoaderRoute: typeof AttendanceViewHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
 '/attendance/register': {
      id: '/attendance/register'
      path: '/attendance/register'
      fullPath: '/attendance/register'
      preLoaderRoute: typeof AttendanceRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }

  }
}


const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPagesPageIdRoute: DashboardPagesPageIdRoute,
  DashboardAgentsRoute,
  DashboardAdminReplyHelpersRoute, // ✅ NEW
  SmartCatalogRoute,
  SmartCatalogPageIdRoute,        // ✅ NEW
  SmartCatalogPageIdAdminRoute,   // ✅ NEW
  DashboardFlowRoute,
  TrackTrackingIdRoute,
  DeliveryRoute,
  DashboardAdminCreateDriverRoute,   // ✅ NEW
  DashboardAdminDeliveriesRoute,     // ✅ NEW
  DashboardDriverRoute,              // ✅ NEW
  DashboardAdminDriverMapRoute,   // ✅ NEW
  AttendanceRoute,
  AttendanceReportRoute,
  AttendanceSettingsRoute,
  AttendanceAdminRolesRoute,
  AttendanceAdminConfigRoute,
  AttendanceViewHistoryRoute,
  AttendanceRegisterRoute,

}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
